spring.application.name=collageFormFillup

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/collageformfillup
spring.datasource.username=root
spring.datasource.password=Dilip@1248

#jpa configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

